Move [Marble [alpha=A, numeric=4], direction=1]
Move [Marble [alpha=A, numeric=4], direction=2]
Move [Marble [alpha=A, numeric=5], direction=1]
Move [Marble [alpha=A, numeric=5], direction=2]
Move [Marble [alpha=A, numeric=5], direction=6]
Move [Marble [alpha=B, numeric=4], direction=2]
Move [Marble [alpha=B, numeric=5], direction=1]
Move [Marble [alpha=B, numeric=5], direction=2]
Move [Marble [alpha=B, numeric=6], direction=1]
Move [Marble [alpha=B, numeric=6], direction=2]
Move [Marble [alpha=B, numeric=6], direction=6]
Move [Marble [alpha=C, numeric=5], direction=1]
Move [Marble [alpha=C, numeric=5], direction=2]
Move [Marble [alpha=C, numeric=5], direction=3]
Move [Marble [alpha=C, numeric=5], direction=5]
Move [Marble [alpha=C, numeric=6], direction=1]
Move [Marble [alpha=C, numeric=6], direction=2]
Move [Marble [alpha=C, numeric=6], direction=3]
Move [Marble [alpha=G, numeric=4], direction=3]
Move [Marble [alpha=G, numeric=4], direction=4]
Move [Marble [alpha=G, numeric=4], direction=5]
Move [Marble [alpha=G, numeric=4], direction=6]
Move [Marble [alpha=G, numeric=5], direction=2]
Move [Marble [alpha=G, numeric=5], direction=3]
Move [Marble [alpha=G, numeric=5], direction=4]
Move [Marble [alpha=G, numeric=5], direction=5]
Move [Marble [alpha=G, numeric=5], direction=6]
Move [Marble [alpha=H, numeric=4], direction=4]
Move [Marble [alpha=H, numeric=4], direction=5]
Move [Marble [alpha=H, numeric=5], direction=4]
Move [Marble [alpha=H, numeric=5], direction=5]
Move [Marble [alpha=H, numeric=6], direction=2]
Move [Marble [alpha=H, numeric=6], direction=4]
Move [Marble [alpha=H, numeric=6], direction=5]
Move [Marble [alpha=I, numeric=5], direction=3]
Move [Marble [alpha=I, numeric=5], direction=4]
Move [Marble [alpha=I, numeric=5], direction=5]
Move [Marble [alpha=I, numeric=6], direction=3]
Move [Marble [alpha=I, numeric=6], direction=4]
Move [Marble [alpha=I, numeric=6], direction=5]
Move [Marble [alpha=A, numeric=4], Marble [alpha=A, numeric=5], direction=6]
Move [Marble [alpha=A, numeric=4], Marble [alpha=B, numeric=4], direction=1]
Move [Marble [alpha=A, numeric=4], Marble [alpha=B, numeric=5], direction=2]
Move [Marble [alpha=A, numeric=4], Marble [alpha=C, numeric=6], direction=2]
Move [Marble [alpha=A, numeric=5], Marble [alpha=B, numeric=4], direction=2]
Move [Marble [alpha=A, numeric=5], Marble [alpha=B, numeric=5], direction=1]
Move [Marble [alpha=A, numeric=5], Marble [alpha=B, numeric=6], direction=2]
Move [Marble [alpha=A, numeric=5], Marble [alpha=C, numeric=5], direction=1]
Move [Marble [alpha=B, numeric=4], Marble [alpha=B, numeric=6], direction=6]
Move [Marble [alpha=B, numeric=4], Marble [alpha=C, numeric=5], direction=2]
Move [Marble [alpha=B, numeric=4], Marble [alpha=C, numeric=5], direction=5]
Move [Marble [alpha=B, numeric=5], Marble [alpha=B, numeric=6], direction=6]
Move [Marble [alpha=B, numeric=5], Marble [alpha=C, numeric=5], direction=1]
Move [Marble [alpha=B, numeric=5], Marble [alpha=C, numeric=6], direction=2]
Move [Marble [alpha=B, numeric=6], Marble [alpha=C, numeric=5], direction=2]
Move [Marble [alpha=B, numeric=6], Marble [alpha=C, numeric=5], direction=5]
Move [Marble [alpha=B, numeric=6], Marble [alpha=C, numeric=6], direction=1]
Move [Marble [alpha=B, numeric=6], Marble [alpha=C, numeric=6], direction=2]
Move [Marble [alpha=C, numeric=5], Marble [alpha=C, numeric=6], direction=1]
Move [Marble [alpha=C, numeric=5], Marble [alpha=C, numeric=6], direction=2]
Move [Marble [alpha=C, numeric=5], Marble [alpha=C, numeric=6], direction=3]
Move [Marble [alpha=G, numeric=4], Marble [alpha=G, numeric=5], direction=3]
Move [Marble [alpha=G, numeric=4], Marble [alpha=G, numeric=5], direction=4]
Move [Marble [alpha=G, numeric=4], Marble [alpha=G, numeric=5], direction=5]
Move [Marble [alpha=G, numeric=4], Marble [alpha=G, numeric=5], direction=6]
Move [Marble [alpha=G, numeric=4], Marble [alpha=H, numeric=4], direction=4]
Move [Marble [alpha=G, numeric=4], Marble [alpha=H, numeric=4], direction=5]
Move [Marble [alpha=G, numeric=4], Marble [alpha=H, numeric=5], direction=5]
Move [Marble [alpha=G, numeric=4], Marble [alpha=I, numeric=6], direction=5]
Move [Marble [alpha=G, numeric=5], Marble [alpha=H, numeric=4], direction=2]
Move [Marble [alpha=G, numeric=5], Marble [alpha=H, numeric=4], direction=5]
Move [Marble [alpha=G, numeric=5], Marble [alpha=H, numeric=5], direction=4]
Move [Marble [alpha=G, numeric=5], Marble [alpha=H, numeric=6], direction=2]
Move [Marble [alpha=G, numeric=5], Marble [alpha=H, numeric=6], direction=4]
Move [Marble [alpha=G, numeric=5], Marble [alpha=H, numeric=6], direction=5]
Move [Marble [alpha=G, numeric=5], Marble [alpha=I, numeric=5], direction=4]
Move [Marble [alpha=H, numeric=4], Marble [alpha=I, numeric=5], direction=5]
Move [Marble [alpha=H, numeric=5], Marble [alpha=I, numeric=5], direction=4]
Move [Marble [alpha=H, numeric=5], Marble [alpha=I, numeric=6], direction=5]
Move [Marble [alpha=H, numeric=6], Marble [alpha=I, numeric=5], direction=2]
Move [Marble [alpha=H, numeric=6], Marble [alpha=I, numeric=5], direction=5]
Move [Marble [alpha=H, numeric=6], Marble [alpha=I, numeric=6], direction=4]
Move [Marble [alpha=I, numeric=5], Marble [alpha=I, numeric=6], direction=3]
